[project]
name = "bennett"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "yubinCloud", email = "yubin_SkyWalker@yeah.net"},
]
dependencies = [
    "nacos-sdk-python>=0.1.16",
    "fastapi>=0.111.0",
    "llama-index>=0.10.55",
]
requires-python = "==3.11.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
