version: '3'
services:
  mysql8:
    build:
      context: ./mysql8
    container_name: ${PROJECT_PREFIX}-${MYSQL_HOST}
    hostname: ${MYSQL_HOST}
    image: ${PROJECT_PREFIX}-${MYSQL_HOST}
    expose:
      - "3306"
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
    privileged: true
    volumes:
      - ./mysql8/volume/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql8/volume/data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "/root/wait-for-it.sh", "localhost:3306"]
      interval: 8s
      timeout: 5s
      retries: 10
      start_period: 45s
    restart: ${DOCKER_RESTART_POLICY}

  redis6:
    build:
      context: ./redis6
    container_name: ${PROJECT_PREFIX}-${REDIS_HOST}
    hostname: ${REDIS_HOST}
    image: ${PROJECT_PREFIX}-${REDIS_HOST}
    privileged: true
    expose:
      - "6379"
  
  sentinel-dashboard:
    build:
      context: ./sentinel-dashboard
    container_name: ${PROJECT_PREFIX}-${SENTINEL_HOST}
    hostname: ${SENTINEL_HOST}
    image: ${PROJECT_PREFIX}-${SENTINEL_HOST}
    expose:
      - "8080"
    ports:
      - 8080:8080
    healthcheck:
      test: ["CMD-SHELL", "curl -sS 'http://localhost:8080/sentinel/#/login' || exit 1"]
      interval: 8s
      timeout: 30s
      retries: 5
      start_period: 30s
    restart: ${DOCKER_RESTART_POLICY}

  gateway:
    build:
      context: ./gateway
    container_name: ${PROJECT_PREFIX}-${GATEWAY_HOST}
    hostname: ${GATEWAY_HOST}
    image: ${PROJECT_PREFIX}-${GATEWAY_HOST}
    ports:
      - ${GATEWAY_INGRESS_PORT}:${GATEWAY_PORT}
    env_file:
      - ./.env
    restart: ${DOCKER_RESTART_POLICY}
  
  sso-auth:
    build:
      context: ./sso-auth
    container_name: ${PROJECT_PREFIX}-${AUTH_SERVICE_HOST}
    hostname: ${AUTH_SERVICE_HOST}
    image: ${PROJECT_PREFIX}-${AUTH_SERVICE_HOST}
    expose:
      - ${AUTH_SERVICE_PORT}
    environment:
      - APP_PORT=${AUTH_SERVICE_PORT:-9590}
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILE}
      - MYSQL_DB=sso_auth  # 存放认证信息的数据库名
    env_file:
      - ./.env
    restart: ${DOCKER_RESTART_POLICY}

  hello-service:
    build:
      context: ./hello-service
    container_name: ${PROJECT_PREFIX}-${HELLO_SERVICE_HOST}
    hostname: ${HELLO_SERVICE_HOST}
    image: ${PROJECT_PREFIX}-${HELLO_SERVICE_HOST}
    expose:
      - "80"
    restart: ${DOCKER_RESTART_POLICY}
