version: '3'
services:
  skywalking-elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.10.2
    container_name: ${PROJECT_PREFIX}-${SKYWALKING_ES_HOST}
    hostname: ${SKYWALKING_ES_HOST}
    expose:
      - 9200
      - 9300
    environment:
      - http.cors.enabled=true
      - http.cors.allow-origin=*
      - bootstrap.memory_lock=true
      - discovery.type=single-node        # 指定单节点模式
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"  # 指定内存限制
    privileged: true
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:9200/_cluster/health"]
      interval: 30s
      timeout: 10s
      retries: 10
      start_period: 800s
    restart: ${DOCKER_RESTART_POLICY}

  skywalking-oap:
    image: apache/skywalking-oap-server:8.9.1
    container_name: ${PROJECT_PREFIX}-${SKYWALKING_OAP_HOST}
    hostname: ${SKYWALKING_OAP_HOST}
    ports:
      - 12800:12800
      - 11800:11800
    environment:
      TZ: Asia/Shanghai
      SW_STORAGE: elasticsearch
      SW_STORAGE_ES_CLUSTER_NODES: ${SKYWALKING_ES_HOST}:9200
      SW_HEALTH_CHECKER: default
    depends_on:
      skywalking-elasticsearch:
        condition: service_healthy
    restart: ${DOCKER_RESTART_POLICY}
  
  skywalking-ui:
    image: apache/skywalking-ui:8.9.1
    container_name: ${PROJECT_PREFIX}-${SKYWALKING_UI_HOST}
    hostname: ${SKYWALKING_UI_HOST}
    ports:
      - 8330:8330
    environment:
      TZ: Asia/Shanghai
      SW_OAP_ADDRESS: ${SKYWALKING_OAP_HOST}:12800
      SERVER_PORT: 8330
    depends_on:
      - skywalking-oap
    restart: ${DOCKER_RESTART_POLICY}