version: '3'
services:
  
  ##################################################################
  #################### Basic infrastructure ########################
  ##################################################################
  mysql8:
    build:
      context: ./mysql8
    container_name: ${PROJECT_PREFIX}-${MYSQL_HOST}
    hostname: ${MYSQL_HOST}
    image: ${PROJECT_PREFIX}-${MYSQL_HOST}
    expose:
      - "3306"
    # ports:
    #   - 3307:3306
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_PWD}
    privileged: true
    volumes:
      - ./mysql8/volume/conf/my.cnf:/etc/mysql/my.cnf
      - ./mysql8/volume/data:/var/lib/mysql
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - platform-net

  redis6:
    build:
      context: ./redis6
    container_name: ${PROJECT_PREFIX}-${REDIS_HOST}
    hostname: ${REDIS_HOST}
    image: ${PROJECT_PREFIX}-${REDIS_HOST}
    privileged: true
    expose:
      - "6379"
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - platform-net
  
  sentinel-dashboard:
    build:
      context: ./sentinel-dashboard
    container_name: ${PROJECT_PREFIX}-${SENTINEL_HOST}
    hostname: ${SENTINEL_HOST}
    image: ${PROJECT_PREFIX}-${SENTINEL_HOST}
    command: ["/wait-for-it.sh", "mysql8:3306", "-t", "0", "--", "sh", "-c", "java -Dauth.enabled=false -jar app.jar --server.servlet.context-path=/sentinel"]
    expose:
      - 8080
    healthcheck:
      test: ["CMD-SHELL", "curl -sS 'http://localhost:8080/sentinel/#/login' || exit 1; echo healthy"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 360s
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - platform-net
  
  nacos:
    build:
      context: ./nacos
    container_name: ${PROJECT_PREFIX}-${NACOS_HOST}
    hostname: ${NACOS_HOST}
    image: ${PROJECT_PREFIX}-${NACOS_HOST}
    env_file:
      - ./nacos/nacos.env
    environment:
      - MYSQL_SERVICE_HOST=${MYSQL_HOST}
      - MYSQL_SERVICE_PORT=3306
      - MYSQL_SERVICE_USER=root
      - MYSQL_SERVICE_PASSWORD=${MYSQL_PWD}
      - MYSQL_SERVICE_DB_NAME=nacos
    expose:
      - "8848"
      - "9848"
      - "9849"
    ports:
      - 8848:8848
      # - 9848:9848
      # - 9849:9849
    healthcheck:
      test: ["CMD-SHELL", "curl -sS 'http://localhost:8848/nacos' || exit 1; echo healthy"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 60s
    depends_on:
      sentinel-dashboard:
        condition: service_healthy
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - platform-net

networks:
  platform-net:
    external: true