server:
  port: ${APP_PORT:9620}
  servlet:
    context-path: /avue-helper

spring:
  application:
    name: @artifactId@
  threads:
    virtual:
      enabled: true
  servlet:
    multipart:
      max-file-size: 30MB
      max-request-size: 50MB
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${MYSQL_HOST:127.0.0.1}:${MYSQL_PORT:3306}/${MYSQL_DB:antv_data_server}?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: ${MYSQL_USERNAME:root}
    password: ${MYSQL_PWD:root}

  cloud:
    nacos:
      discovery:
        server-addr: http://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}

minio:
  url: ${AVUE_HELPER_MINIO_HOST:http://127.0.0.1:9000}
  bucket: avue
  access-key: ${AVUE_HELPER_MINIO_ACCESS_KEY:admin}
  secret-key: ${AVUE_HELPER_MINIO_SECRET_KEY:inet_store@2018}


mybatis:
  mapper-locations: classpath:mapper/*.xml

springdoc:
  swagger-ui:
    path: /docs
knife4j:
  enable: true
  setting:
    language: zh_cn

management:
  endpoints:
    web:
      exposure:
        include: health