server:
  port: ${APP_PORT:10013}
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: http://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

sidecar:
  ip: ${AVUE_NGINX_HOST:127.0.0.1}
  port: ${AVUE_NINGX_PORT:8095}
  health-check-url: http://${AVUE_NGINX_HOST:127.0.0.1}:${AVUE_NINGX_PORT:8095}/health

management:
  endpoint:
    health:
      show-details: always
