server:
  port: ${APP_PORT:10010}


spring:
  application:
    name: @artifactId@
  profiles:
    active: dev
  data:
    redis:
      database: ${REDIS_DB:1}
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  cloud:
    nacos:
      server-addr: http://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
    discovery:
      client:
        simple:
          instances:
            sentinel-dashboard:
              - uri: http://${SENTINEL_HOST:127.0.0.1}:${SENTINEL_PORT:8080}
            nacos:
              - uri: http://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}

    gateway:
      httpclient:
        websocket:
          max-frame-payload-length: 10485760
      routes:
        - id: sentinel-dashboard
          uri: lb://sentinel-dashboard
          predicates:
            - Path=/sentinel/**

        - id: nacos
          uri: lb://nacos
          predicates:
            - Path=/nacos/**

        - id: sso-auth
          uri: lb://sso-auth
          predicates:
            - Path=/auth/**

        - id: jupyter-websocket-gateway
          uri: lb:ws://jupyter-service
          predicates:
            - Path=/ws/**
          filters:
            - JupyterAuthAdapter

        - id: jupyter-service
          uri: lb://jupyter-service
          predicates:
            - Path=/jupyter/**
          filters:
            - JupyterAuthAdapter

        - id: xxl-job-admin
          uri: lb://xxl-job-admin
          predicates:
            - Path=/xxl-job-admin/**

        - id: avue-nginx
          uri: lb://avue-nginx
          predicates:
            - Path=/avue-download/**
          filters:
            - StripPrefix=1

        - id: avue-data-server
          uri: lb://avue-data-server
          predicates:
            - Path=/avue/**
          filters:
            - StripPrefix=1

        - id: ds-worker
          uri: lb://ds-worker
          predicates:
            - Path=/ds-worker/**

        - id: ds-coordinator
          uri: lb://ds-coordinator
          predicates:
            - Path=/ds-coordinator/**
          filters:
            - StripPrefix=1

        - id: af-askari
          uri: lb://af-askari
          predicates:
            - Path=/af-askari/**
          filters:
            - StripPrefix=1

      globalcors:
        cors-configurations:
          '[/**]':
            allowedOriginPatterns: "*"
            allowed-methods: "*"
            allowed-headers: "*"
            allow-credentials: true
            exposedHeaders: "Content-Disposition,Content-Type,Cache-Control"
        add-to-simple-url-handler-mapping: true
    openfeign:
      httpclient:
        enabled: true
        max-connections: 200
        max-connections-per-route: 50




sa-token:
  token-name: authz
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  jwt-secret-key: ${JWT_SECRET:sfaisokhnfsdsadaitfasf}


management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: gateway,health