server:
  port: ${APP_PORT:10010}

spring:
  application:
    name: @artifactId@
  profiles:
    active: dev
  data:
    redis:
      database: ${REDIS_DB:1}
      host: ${REDIS_HOST:127.0.0.1}
      port: ${REDIS_PORT:6379}
      timeout: 10s
      lettuce:
        pool:
          max-active: 200
          max-wait: -1ms
          max-idle: 10
          min-idle: 0
  cloud:
    discovery:
      client:
        simple:
          instances:
            sentinel-dashboard:
              - uri: http://${SENTINEL_HOST:127.0.0.1}:${SENTINEL_PORT:8080}
            auth-service:
              - uri: http://${AUTH_SERVICE_HOST:127.0.0.1}:${AUTH_SERVICE_PORT:9590}
            hello-service:
              - uri: http://${HELLO_SERVICE_HOST:127.0.0.1}:${HELLO_SERVICE_PORT:80}
    gateway:
      routes:
        - id: sentinel-dashboard
          uri: lb://sentinel-dashboard
          predicates:
            - Path=/sentinel/**

        - id: sso-auth
          uri: lb://auth-service
          predicates:
            - Path=/auth/login/**,/auth/admin/**

        - id: hello-service
          uri: lb://hello-service
          predicates:
            - Path=/hello/**
          filters:
            - StripPrefix=1

sa-token:
  token-name: authorization
  timeout: 2592000
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: uuid
  is-log: false
  jwt-secret-key: ${JWT_SECRET:sfaisokhnfsdsadaitfasf}


management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: gateway
