server:
  port: ${APP_PORT:10017}
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: http://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

sidecar:
  ip: ${SIMULATOR_HOST:127.0.0.1}
  port: ${SIMULATOR_PORT:9660}
  health-check-url: http://${SIMULATOR_HOST:127.0.0.1}:${SIMULATOR_PORT:9660}/health

management:
  endpoint:
    health:
      show-details: always
