version: '3'
services:
  # ********************************************************
  # ************** encryption-gateway **********************
  # ********************************************************
  af-encryption-gateway:
    build:
      context: ./af-encryption-gateway
    container_name: af-encryption-gateway
    hostname: af-encryption-gateway
    image: af-encryption-gateway
    ports:
      - 10500:10500
    env_file:
      - ./.env
    networks:
      - platform-net
  
  # ********************************************************
  # ******************** DynamicAPI ************************
  # ********************************************************
  af-dynamicapi-worker:
    build:
      context: ./af-dynamicapi/worker
    container_name: af-dynamicapi-worker
    hostname: af-dynamicapi-worker
    image: af-dynamicapi-worker
    expose:
      - 7100
    environment:
      - ENV_FOR_DYNACONF=production
    healthcheck:
      test: ["CMD", "wget http://127.0.0.1:7100/health/live -q -O /dev/null"]
      interval: 5s
      timeout: 5s
      retries: 5
    networks:
      - platform-net
  
  # ********************************************************
  # ********************** askari  *************************
  # ********************************************************
  af-askari:
    build:
      context: ./af-askari
    container_name: af-askari
    hostname: af-askari
    image: af-askari
    expose:
      - 10510
    networks:
      - platform-net
  
  # ********************************************************
  # ******************** sidecars **************************
  # ********************************************************
  sidecar-af-askari:
    build:
      context: ../alibaba-sidecars/af-askari
    container_name: aet-sidecar-af-askari
    hostname: sidecar-af-askari
    image: aet-sidecar-af-askari
    expose:
      - ${SIDECAR_AF_ASKARI_PORT}
    env_file:
      - ./.env
    environment:
      - APP_PORT=${SIDECAR_AF_ASKARI_PORT}
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - platform-net
  
  sidecar-dynamicapi:
    build:
      context: ../alibaba-sidecars/dynamic-api
    container_name: aet-sidecar-dynamicapi
    hostname: sidecar-dynamicapi
    image: aet-sidecar-dynamicapi
    expose:
      - ${SIDECAR_DYNAMICAPI_PORT}
    env_file:
      - ./.env
    environment:
      - APP_PORT=${SIDECAR_DYNAMICAPI_PORT}
    restart: ${DOCKER_RESTART_POLICY}
    networks:
      - platform-net

networks:
  platform-net:
    external: true