apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql8-data-pvc
  namespace: aet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi
