apiVersion: apps/v1
kind: Deployment
metadata:
  name:  avue-helper
  namespace: aet
  labels:
    k8s.kuboard.cn/layer: svc
    k8s.kuboard.cn/name: avue-helper
spec:
  selector:
    matchLabels:
      app: avue-helper
  replicas: 1
  template:
    metadata:
      labels:
        app: avue-helper
    spec:
      containers:
        - name: avue-helper
          image: aet-avue-helper
          imagePullPolicy: Never
          ports:
          - containerPort: 9620
          envFrom:
            - configMapRef:
                name: public-env
          env:
            - name: AVUE_HELPER_MINIO_HOST
              value: http://minio-server:9000
            - name: AVUE_HELPER_MINIO_ACCESS_KEY
              valueFrom:
                configMapKeyRef:
                  name: public-env
                  key: MINIO_ROOT_USER
            - name: AVUE_HELPER_MINIO_SECRET_KEY
              valueFrom:
                configMapKeyRef:
                  name: public-env
                  key: MINIO_ROOT_PASSWORD
---

kind: Service
apiVersion: v1
metadata:
  name: avue-helper
  namespace: aet
spec:
  selector:
    app: avue-helper
  type: ClusterIP
  clusterIP: None
  ports:
  - port:  9620
    targetPort:  9620