server:
  port: ${APP_PORT:9592}
  servlet:
    context-path: /euser-sso

spring:
  application:
    name: @artifactId@
  threads:
    virtual:
      enabled: true
  data:
    redis:  # used for sa-token
      database: ${EUSER_SSO_REDIS_DB:2}
      host: ${EUSER_SSO_REDIS_HOST:127.0.0.1}
      port: ${EUSER_SSO_REDIS_PORT:6379}
    af-redis:  # used for cache public-api permission
      database: ${EUSER_SSO_AF_REDIS_DB:1}
      host: ${EUSER_SSO_AF_REDIS_HOST:127.0.0.1}
      port: ${EUSER_SSO_AF_REDIS_PORT:6379}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${EUSER_SSO_PG_HOST:127.0.0.1}:${EUSER_SSO_PG_PORT:5432}/euser_sso
    username: ${EUSER_SSO_PG_USER:postgres}
    password: ${EUSER_SSO_PG_PASSWORD:postgres}

  cloud:
    nacos:
      discovery:
        server-addr: http://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}

memcached:
  host: ${EUSER_SSO_MEMCACHED_HOST:127.0.0.1}
  port: ${EUSER_SSO_MEMCACHED_PORT:11211}
  username: ${EUSER_SSO_MEMCACHED_USERNAME:admin}
  password: ${EUSER_SSO_MEMCACHED_PASSWORD:inet_store@2018}

# 山东通对接参数
sdt:
  enabled: ${EUSER_SSO_SDT_ENABLED:false}
  endpoint-url: ${EUSER_SSO_SDT_ENDPOINT_URL:http://15.209.0.3:80}
  corp-id: ${EUSER_SSO_SDT_CORPID:wwafa1a3005a15a672}
  agent-id: ${EUSER_SSO_SDT_AGENTID:1004649}
  secret: ${EUSER_SSO_SDT_SECRET:GYdb6LBh-FR3Eu-1bhmLXw_YavBdqUXwce5ooSz_hFc}


sa-token:
  token-name: eauth
  timeout: 259200
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-128
  is-print: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml

management:
  endpoint:
    health:
      enabled: true

knife4j:
  enable: true