server:
  port: ${APP_PORT:9592}
  servlet:
    context-path: /euser-sso

spring:
  application:
    name: @artifactId@
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${EUSERSSO_PG_HOST:127.0.0.1}:${EUSERSSO_PG_PORT:5432}/euser_sso
    username: ${EUSERSSO_PG_USER:postgres}
    password: ${EUSERSSO_PG_PASSWORD:postgres}

  cloud:
    nacos:
      discovery:
        server-addr: http://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}

sa-token:
  token-name: eauth
  timeout: 259200
  activity-timeout: -1
  is-concurrent: true
  is-share: true
  token-style: random-128
  is-print: false


mybatis:
  mapper-locations: classpath:mapper/*.xml
  config-location: classpath:mybatis-config.xml
