server:
  port: ${APP_PORT:10011}
spring:
  application:
    name: @artifactId@
  cloud:
    nacos:
      discovery:
        server-addr: http://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

sidecar:
  ip: ${JUPYTER_HOST:10.245.142.209}
  port: ${JUPYTER_PORT:8092}

management:
  endpoint:
    health:
      show-details: always
