apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-server-pvc
  namespace: aet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
