server:
  port: ${APP_PORT:9719}
  servlet:
    context-path: /chat-analysis

spring:
  application:
    name: @artifactId@
  threads:
    virtual:
      enabled: true
  cloud:
    nacos:
      server-addr: http://${NACOS_HOST:127.0.0.1}:${NACOS_PORT:8848}
  data:
    redis:
      database: ${CHAT_ANALYSIS_REDIS_DB:1}
      host: ${CHAT_ANALYSIS_REDIS_HOST:127.0.0.1}
      port: ${CHAT_ANALYSIS_REDIS_PORT:6379}
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${CHAT_ANALYSIS_PG_HOST:127.0.0.1}:${CHAT_ANALYSIS_PG_PORT:5432}/chat_analysis
    username: ${CHAT_ANALYSIS_PG_USER:postgres}
    password: ${CHAT_ANALYSIS_PG_PASSWORD:postgres}

ai-serv:
  # 配置 AI 服务的 backend，可选：`local-test`、`transn` 等，具体可见 `AIServBackendEnum` 类
  backend: ${CHAT_ANALYSIS_AI_SRV_BACKEND:openai}
  transn-backend:
    base-url: ${TRANSN_BACKEND_BASEURL:https://zx.poc.iol8.com}
  openai:
    model-name: ${OPENAI_MODEL_NAME:gpt-3.5-turbo}
    api-key: ${OPENAI_API_KEY:sk-pNJrQLPQp5016oo7C23834265c7142Ec94Ad6a368bDa83F8}
    base-url: ${OPENAI_BASE_URL:https://hk.xty.app/v1}