apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: af-etcd-data-pvc
  namespace: aet
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 500M
